---
# --- Visualization plotly config ---
config:
  dynamic_file: "../results/Dynamic2.txt"
  static_file: "../results/Static2.txt"
  neighbors_file: "../results/neighbors2.txt"
  L: 20
  M: 4
  R: 1

#  for ovito
  particle: 311
...